### ISSUE TITLE
Automatic switching between BUILD_CACHE and USE_CACHE

### ISSUE THREAD

**Issue by matthijskooijman** [cltrudeau/django-airplane#4]
It would be nice if airplane would just work automatically, downloading resources when possible/needed, and then using the cache automatically when the cache is valid.

A naive implementation would download the resources when they are not in the cache, and then serve them locally when the *are* in the cache. This probably works in most cases, since the url typically includes the version number so changes when the resource change. If the the resource on the server changes without the url changing, this might cause an outdated cache.

One way to deal with this is to re-download (or at least try to) whenever the server restarts (though that might be too often when you include autoreloads of the dev server, so maybe only explicit reloads). If documented properly, this would probably be sufficient (just let people restart the dev server if the resource change).

One other issue is that when the internet connection is unavailable or flaky, you might end up downloading an invalid or empty file into the cache. Again, a restart could fix this. An alternative would be to pass the *entire* script tag (for scripts) to airplane and include an `integrity` attribute with a hash of the file.

Just some thoughts on making airplane even a bit better :-)

**Comment by cltrudeau** [comment]
Thanks for the thoughts Matthijs. I'm glad someone is getting some use out of this. I kind of just threw it together to solve a problem I had.

I like this suggestion. I think what I'll do is add a third mode, that way nothing existing will break.

**Comment by cltrudeau** [comment]
Thanks again for the ideas. AUTO_CACHE is now available with the new release.

In order to clean some stuff up, I removed py2 support. Hopefully you're using py3 and can take advantage of the new features.
