### ISSUE TITLE
(Docs about) installation of airplane

### ISSUE THREAD

**Issue by matthijskooijman** [cltrudeau/django-airplane#5]
I just installed airplane and it works nicely. I was a little bit puzzled about the installation, though. In particular:
 - I missed adding the app to `INSTALLED_APPS`. Looking again, it is actually documented, but maybe it would be more obvious if there was a code block, that shows this.
 - The configuration (and the code, I noticed later) refers to `BASE_DIR` setting, but AFAIK this is not a default Django setting but just a conventional name for the project directory?

   Thinking about this, it is a bit fragile that airplane defaults to `BASE_DIR` + `airplane.CACHE_DIR` internally, and the recommended configuration duplicates this join in the `STATICFILES_DIR` (with the possibility of ending up with different values).

   I wonder if it would be better to just recommend people to set the `AIRPLANE_CACHE` variable to an absolute path (maybe even require this, perhaps after a deprecation warning) and always do the needed path join in their settings explicitly. e.g.:

       AIRPLANE_CACHE = join(BASE_DIR, airplane.CACHE_DIR)                                                                  
       STATICFILES_DIRS += (                                                                                                        
           AIRPLANE_CACHE,                                                                                                          
       )

**Comment by cltrudeau** [comment]
I'm wary of changing how the cache parm is built as this library doesn't get updated all that often and I don't want to deal with the deprecation problem. I will make the docs more clear though.

**Comment by cltrudeau** [comment]
I'm building some of your suggestions and dug into the code a bit more. It looks like the AIRPLANE_CACHE setting can already take either a fully qualified path or a path relative to BASE_DIR. I'll update the docs to make this a bit clearer.

BASE_DIR is now defined in a project created with the django-admin script, so although it isn't "official" it is pretty "official" :)

**Comment by cltrudeau** [comment]
I've exposed an internal method which returns the full path of the cache. You can now do "airplane.cache_path()" inside of your STATIC_DIR setting. Docs have been updated.
